apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd

spec:
  project: health

  source:
    repoURL: https://charts.redpanda.com
    chart: redpanda
    targetRevision: 5.8.12
    helm:
      values: |
        statefulset:
          replicas: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: datacluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
