apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
spec:
  project: health
  source:
    repoURL: git@github.com:lilianasacorreia/health-redpanda.git
    path: helm/redpanda
    targetRevision: main
    helm:
      chart: redpanda
      repo: https://charts.redpanda.com
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: datacluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
